# Generated by Django 3.2.9 on 2021-11-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creaetd',
            new_name='created',
        ),
    ]
